# Generated by Django 3.0.6 on 2020-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_python_app', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
